### ISSUE TITLE
大佬，可以加我QQ指导我一下吗？

### ISSUE THREAD

**Issue by g5an** [johnzhaoican/ASUS-TUF-B365M-Plus-Gaming--hackintosh-EFI#1]
我主板跟你的一样，折腾了两天四叶草引导，装完起来的时候黑屏。
所以想试试你这个，可以加我指导一下吗? 944031246

**Comment by johnzhaoican** [comment]
你好，首先你要升级到最新的BIOS，然后关掉一些我方案里面的选项才可以成功。
如果可以的话麻烦你把所遇到的问题图文方式放在这里，这样也会方便后来的朋友参考，同时我也会尽力的帮助你

**Comment by g5an** [comment]
> 你好，首先你要升级到最新的BIOS，然后关掉一些我方案里面的选项才可以成功。
> 如果可以的话麻烦你把它遇到的问题图文方式放在这里，这样也会方便后来的朋友参考，同时我也会尽力的帮助你

谢谢大佬指点，不过我已经找到问题了，是因为我一开始用hdmi输出，所以黑屏，买了个主动式的DP转HDMI就好了。但有一个问题我解决不了。就是通过修补这款主板的缓冲区。让他能从主板的hdmi口输出，这个我参照网站的教程还是不行
就是config.plist 下面的 DeviceProperties 属性

**Comment by johnzhaoican** [comment]
> > 你好，首先你要升级到最新的BIOS，然后关掉一些我方案里面的选项才可以成功。
> > 如果可以的话麻烦你把它遇到的问题图文方式放在这里，这样也会方便后来的朋友参考，同时我也会尽力的帮助你
> 
> 谢谢大佬指点，不过我已经找到问题了，是因为我一开始用hdmi输出，所以黑屏，买了个主动式的DP转HDMI就好了。但有一个问题我解决不了。就是通过修补这款让他能从主板的hdmi口输出，这个我参照网站的教程还是不行
> 就是config.plist下面的DeviceProperties属性

内置GPU我已在config.plist里设置用于显示输出，而我测试过是能正常的，请把你的硬件配置也发下让我好参考一起研究问题所在
