### ISSUE TITLE
请问用i7-9700可以安装吗？

### ISSUE THREAD

**Issue by chujiezheng** [johnzhaoican/ASUS-TUF-B365M-Plus-Gaming--hackintosh-EFI#2]

**Comment by johnzhaoican** [comment]
可以的，主板一样就行

**Comment by chujiezheng** [comment]
抱歉，我漏看了你的显卡。我是不装显卡的，请问我需要怎么修改呢？

**Comment by johnzhaoican** [comment]
单显示器的话不用改，直接用就行！记得不要接VGA接口

**Comment by chujiezheng** [comment]
好的，十分感谢你的帮助！

**Comment by chujiezheng** [comment]
> 单显示器的话不用改，直接用就行！记得不要接VGA接口

用核显的话，显存直接就是1.5G了吗？我用背后的DP接显示器

**Comment by johnzhaoican** [comment]
> > 单显示器的话不用改，直接用就行！记得不要接VGA接口
> 
> 用核显的话，显存直接就是1.5G了吗？我用背后的DP接显示器

1.5G不够吗？你电脑的用途是...????

**Comment by chujiezheng** [comment]
哈哈够的，我的意思是会不会出现配置不对导致核显只有几十M的情况

**Comment by johnzhaoican** [comment]
这个是可以修改的，不过我觉得1.5G也有点高了，用不了这么多。建议你来个4K显示器来的实际一点，会有惊喜，哈哈
